### PR TITLE
sha1: Add extra .S for AArch64 on macOS (Fixing building on M1 Macs)

### LINKED ISSUE #28: sha1: Apple M1 build failures
As discovered on #27, the `aarch64` assembly for the `sha1` ~~and `sha2`~~ (edit: SHA-256 support added in #35) crates does not compile on macOS/M1:

```
Compiling sha2-asm v0.5.4
The following warnings were emitted during compilation:

warning: src/sha256_aarch64.S:64:2: error: ADR/ADRP relocations must be GOT relative
warning:  adrp x2, .K
warning:  ^
warning: src/sha256_aarch64.S:64:2: error: unknown AArch64 fixup kind!
warning:  adrp x2, .K
warning:  ^
warning: src/sha256_aarch64.S:65:2: error: unknown AArch64 fixup kind!
warning:  add x2, x2, :lo12:.K
warning:  ^

error: failed to run custom build command for `sha2-asm v0.5.4`
```

### PR DESCRIPTION
**Pull request by tlercher**
I applied the same fix as in #35 to the `sha1` version with `@PAGE` for addressing and `@PAGEOFF` for loading.

It might not be an ideal solution, but it works for me and fixes #28 on my machine.

### CODE REVIEW

**Comment by tarcieri** [comment]
I'm on vacation and away from my M1, so I'm unable to confirm this works correctly at this time.

I'd prefer to wait until I can do that (or another projector contributor can) before merging this.

**Review by newpavlov — COMMENTED** [review]
I do not (and prefer not to) own any Apple devices, so I can't test this PR. But at the first glance it looks good.

**Comment by tarcieri** [comment]
I’ll be able to test it in a few days

**Comment by Absolucy** [comment]
Is there any reason why `target_os == "macos"` is used instead of  `target_vendor == "apple"`? The build error is also present on iOS targets.

**Comment by tarcieri** [comment]
I can confirm it builds. I would suggest adopting @Absolucy's suggestion to use `target_vendor == "apple"` so it works on iOS as well

**Comment by tlercher** [comment]
Quite the nice solution, thanks for the Input! I added a commit which is also renaming the files (+ fixing `sha2` too)

**Review by tarcieri — APPROVED** [review]
LGTM! Thank you!

@newpavlov any objections to merging this?

**Comment by newpavlov** [comment]
@tarcieri 
No objections. Feel free to merge and cut a release.

**Comment by tarcieri** [comment]
Okay, `sha1-asm` v0.5.1 has been released. However, the `sha-1` crate still needs to be bumped to use v0.5.x of `sha1-asm`.

**Pull request merged**
